micronaut:
  application:
    name: micronaut-test
mongodb:
  uri: mongodb://mongoadmin:secret@${MONGO_HOST:mongo1}:${MONGO_PORT:27017}
netty:
  default:
    allocator:
      max-order: 3
db:
  name: 'test'
  collection: 'football'