micronaut:
  application:
    name: micronautTest
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/test
netty:
  default:
    allocator:
      max-order: 3
db:
  name: 'test'
  collection: 'fruit'